<?php 
function webskillet_admin_preprocess_media_dialog_page(&$vars) {
//dpm($vars['page']['content']['system_main']['tabset']['tabs']);
	foreach ($vars['page']['content']['system_main']['tabset']['tabs']['#primary']
	as $key => $element) {
		$vars['page']['content']['system_main']['tabset']['tabs']['#primary'][$key]['element']['#markup'] = str_replace('Library (MBP)','Media Library',$element['element']['#markup']);
//		dpm($element);
//		$vars['page']['content']['system_main']['tabset']['tabs']['#primary'][$key]['element']['#markup'] = 'stuff';

	}
//	$vars['page']['content']['system_main']['tabset']['tabs']['#primary'] = array();
}
